# Generated by Django 6.1.1 on 2026-09-13 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='posts_curtidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='republicacoes', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(condition=models.Q(('original__isnull', False)), fields=('autor', 'original'), name='uma_republicacao_por_usuario'),
        ),
    ]
