# Generated by Django 6.1.1 on 2026-09-13 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comentario_curtidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='resposta_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='posts.comentario'),
        ),
    ]
