# Generated by Django 6.1.1 on 2026-09-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comentario_resposta_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens_posts/'),
        ),
    ]
