# Generated by Django 6.1.1 on 2026-09-14 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_posts/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='posts.post')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
