# Generated by Django 6.1.1 on 2026-09-14 03:26

from django.db import migrations, models


def preencher_hashtags_existentes(apps, schema_editor):
    import re

    from django.utils.text import slugify

    Hashtag = apps.get_model("posts", "Hashtag")
    Post = apps.get_model("posts", "Post")
    padrao = re.compile(r"(?<![\w#])#([\w]+)", re.UNICODE)

    for post in Post.objects.all().iterator():
        hashtags = []
        for correspondencia in padrao.finditer(post.conteudo or ""):
            nome = correspondencia.group(1)
            slug = slugify(nome)
            if slug:
                hashtag, _ = Hashtag.objects.get_or_create(slug=slug, defaults={"nome": nome})
                hashtags.append(hashtag)
        post.hashtags.set(hashtags)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_imagempost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.hashtag'),
        ),
        migrations.RunPython(preencher_hashtags_existentes, migrations.RunPython.noop),
    ]
