# Generated by Django 6.1.1 on 2026-09-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_hashtag_post_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens_comentarios/'),
        ),
    ]
