# Generated by Django 6.1.1 on 2026-09-14 03:48

from django.db import migrations, models


def preencher_hashtags_dos_comentarios(apps, schema_editor):
    import re

    from django.utils.text import slugify

    Hashtag = apps.get_model("posts", "Hashtag")
    Comentario = apps.get_model("posts", "Comentario")
    padrao = re.compile(r"(?<![\w#])#([\w]+)", re.UNICODE)

    for comentario in Comentario.objects.all().iterator():
        hashtags = []
        for correspondencia in padrao.finditer(comentario.conteudo or ""):
            nome = correspondencia.group(1)
            slug = slugify(nome)
            if slug:
                hashtag, _ = Hashtag.objects.get_or_create(slug=slug, defaults={"nome": nome})
                hashtags.append(hashtag)
        comentario.hashtags.set(hashtags)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comentario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='comentarios', to='posts.hashtag'),
        ),
        migrations.RunPython(preencher_hashtags_dos_comentarios, migrations.RunPython.noop),
    ]
