# Generated by Django 6.1.1 on 2026-09-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comentario_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='audio',
            field=models.FileField(blank=True, upload_to='audios_comentarios/'),
        ),
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, upload_to='audios_posts/'),
        ),
    ]
