# Generated by Django 6.1.1 on 2026-09-14 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_comentario_audio_post_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='salvos_por',
            field=models.ManyToManyField(blank=True, related_name='posts_salvos', to=settings.AUTH_USER_MODEL),
        ),
    ]
