# Generated by Django 6.1.1 on 2026-09-15 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_salvos_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DenunciaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('spam', 'Spam'), ('assedio', 'Assédio'), ('odio', 'Discurso de ódio'), ('sexual', 'Conteúdo sexual'), ('violencia', 'Violência'), ('informacao_pessoal', 'Informação pessoal'), ('outro', 'Outro')], max_length=32)),
                ('detalhes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('resolvida', 'Resolvida'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='posts.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('denunciante', 'post'), name='denuncia_post_unica')],
            },
        ),
        migrations.CreateModel(
            name='PostSemInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignorado_por', to='posts.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_sem_interesse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'post'), name='post_sem_interesse_unico')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueado_por', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_bloqueados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'bloqueado'), name='usuario_bloqueado_unico'), models.CheckConstraint(condition=models.Q(('usuario', models.F('bloqueado')), _negated=True), name='usuario_nao_bloqueia_a_si_mesmo')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSilenciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('silenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silenciado_por', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_silenciados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'silenciado'), name='usuario_silenciado_unico'), models.CheckConstraint(condition=models.Q(('usuario', models.F('silenciado')), _negated=True), name='usuario_nao_silencia_a_si_mesmo')],
            },
        ),
    ]
