# Generated by Django 6.1.1 on 2026-09-15 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitir_novas_conversas', models.BooleanField(default=True)),
                ('mensagens_de', models.CharField(choices=[('todos', 'Todas as pessoas'), ('seguindo', 'Somente pessoas que sigo'), ('ninguem', 'Ninguém')], default='todos', max_length=12)),
                ('notificacoes_site', models.BooleanField(default=True)),
                ('notificar_seguidores', models.BooleanField(default=True)),
                ('notificar_curtidas', models.BooleanField(default=True)),
                ('notificar_comentarios', models.BooleanField(default=True)),
                ('notificar_respostas', models.BooleanField(default=True)),
                ('notificar_reposts', models.BooleanField(default=True)),
                ('notificar_mensagens', models.BooleanField(default=True)),
                ('tema', models.CharField(choices=[('sistema', 'Sistema'), ('escuro', 'Escuro'), ('claro', 'Claro')], default='sistema', max_length=8)),
                ('tamanho_fonte', models.CharField(choices=[('pequena', 'Pequena'), ('padrao', 'Padrão'), ('grande', 'Grande')], default='padrao', max_length=8)),
                ('reduzir_animacoes', models.BooleanField(default=False)),
                ('densidade', models.CharField(choices=[('confortavel', 'Confortável'), ('compacta', 'Compacta')], default='confortavel', max_length=11)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
