# Generated by Django 6.1.1 on 2026-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_criar_preferencias_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasusuario',
            name='desativada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenciasusuario',
            name='reativacao_envios_na_janela',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preferenciasusuario',
            name='reativacao_janela_envio_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenciasusuario',
            name='reativacao_ultimo_envio_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenciasusuario',
            name='token_reativacao_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenciasusuario',
            name='token_reativacao_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
