# Generated by Django 6.1.1 on 2026-09-16 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('chave', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disponivel_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('bloqueado_em', models.DateTimeField(blank=True, null=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('descartado_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['criado_em', 'pk'],
                'indexes': [models.Index(fields=['processado_em', 'descartado_em', 'disponivel_em'], name='outbox_pendente_idx'), models.Index(fields=['bloqueado_em'], name='outbox_lock_idx')],
            },
        ),
    ]
