# Generated by Django 6.1.1 on 2026-09-14 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteAutenticacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=64, unique=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('janela_iniciada_em', models.DateTimeField()),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(blank=True, max_length=64)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('verificado_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('ultimo_envio_em', models.DateTimeField(blank=True, null=True)),
                ('janela_reenvio_em', models.DateTimeField(blank=True, null=True)),
                ('reenvios_na_janela', models.PositiveSmallIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
