# Generated by Django 6.1.1 on 2026-09-14 01:49

from django.db import migrations, models


def preencher_chaves(apps, schema_editor):
    Conversa = apps.get_model("mensagens", "Conversa")
    for conversa in Conversa.objects.using(schema_editor.connection.alias).all().iterator():
        ids = list(conversa.participantes.order_by("pk").values_list("pk", flat=True)[:3])
        if len(ids) != 2:
            continue
        chave = f"{ids[0]}:{ids[1]}"
        if not Conversa.objects.using(schema_editor.connection.alias).filter(chave=chave).exists():
            Conversa.objects.using(schema_editor.connection.alias).filter(pk=conversa.pk).update(chave=chave)


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='chave',
            field=models.CharField(blank=True, editable=False, max_length=45, null=True, unique=True),
        ),
        migrations.RunPython(preencher_chaves, migrations.RunPython.noop),
    ]
