# Generated by Django 6.1.1 on 2026-09-16 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_conversa_chave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='chave_idempotencia',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='mensagem',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_idempotencia__isnull', False)), fields=('autor', 'chave_idempotencia'), name='mensagem_idempotencia_unica'),
        ),
    ]
