# Generated by Django 6.1.1 on 2026-09-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
