# Generated by Django 6.1.1 on 2026-09-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_perfil_seguindo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banners_perfil/'),
        ),
    ]
