# Generated by Django 6.1.1 on 2026-09-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_perfil_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
