# Generated by Django 6.1.1 on 2026-09-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_editado_em_denunciapost_postseminteresse_and_more'),
        ('profile', '0006_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='post_fixado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixado_em_perfis', to='posts.post'),
        ),
    ]
