# Generated by Django 6.1.1 on 2026-09-16 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_perfil_post_fixado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('spam', 'Spam'), ('assedio', 'Assédio'), ('odio', 'Discurso de ódio'), ('falsa_identidade', 'Falsa identidade'), ('sexual', 'Conteúdo sexual'), ('violencia', 'Violência ou ameaça'), ('informacao_pessoal', 'Informação pessoal'), ('outro', 'Outro')], max_length=32)),
                ('detalhes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('resolvida', 'Resolvida'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_de_perfil_recebidas', to=settings.AUTH_USER_MODEL)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_de_perfil_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('denunciante', 'alvo'), name='denuncia_usuario_unica'), models.CheckConstraint(condition=models.Q(('denunciante', models.F('alvo')), _negated=True), name='usuario_nao_denuncia_a_si_mesmo')],
            },
        ),
    ]
