# Generated by Django 6.1.1 on 2026-09-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_denunciausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
