# Generated by Django 6.1.1 on 2026-09-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('seguidor', 'Novo seguidor'), ('curtida', 'Curtida'), ('curtida_comentario', 'Curtida em comentário'), ('comentario', 'Comentário'), ('resposta', 'Resposta'), ('repost', 'Repost')], max_length=30),
        ),
    ]
