# Generated by Django 6.1.1 on 2026-09-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='chave_evento',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
    ]
